# -*- coding: utf-8 -*-
"""Ostad-AI-Bootcamp-B8-M1-C2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OmwTCMVKYqlPl-HPPlXcgx6H7hZfG6uT

## Table of Contents
- Displaying Text using `print()` funtion
- Variables in Python
- Basic Data Types (`int`, `float`, `str`, `bool`)
- Commenting in Python
- Type Conversion (`int()`, `float()`, `str()`)
- Arithmatic and Comarison Operators
- Taking User Input in Python
- String Concatenation and Repeatation
- Output formatting using `print()`
- Basics of Debugging

## Displaying Text using `print()` function
"""

print("Hello World")
print('My name is Saihan')

print(17+3)
print(10*5-1/5*4+3)

"""## Variables in Python

Suppose we want to display the addition, subtraction, multiplication, and division of two numbers

 ```python
print(90+10)
print(90-10)
print(90*10)
print(90/10)
 ```

```python
print(20+5)
print(20-5)
print(20*5)
print(20/5)
```

❗ Do you see the problem?

Every time we want to change the numbers, we must write four new lines again and again.
This is repetitive and inefficient.

✔️ This is where variables help!

A variable is simply a name that stores data.
Once values are stored in variables, we can reuse them anytime.

```python
a = 80
b = 10

print(a + b)
print(a - b)
print(a * b)
print(a / b)
```

Here `a` and `b` are variables. Now, if you want to calculate using different numbers,
you only need to change `a` and `b`.


| Data Type   | Python Name | What it means                                  | Example                            |
|-------------|------------ |------------------------------------------------|------------------------------------|
| Integers    | int         | Whole numbers (no decimal point)               | `5`, `-3`, `0`, `1000`             |
| Floats      | float       | Numbers with decimal points                    | `3.14`, `-0.5`, `100.0`, `2.0`     |
| Strings     | str         | Text (anything inside quotes)                  | `"Hello"`, `'Python'`, `"2026"`    |
| Booleans    | bool        | True or False values                           | `True`, `False`, `5 > 3` → `True`  |

"""

a = 30
b = 15

print(a + b)
print(a - b)
print(a * b)
print(a / b)

name = "Abdullah"
print(name)

country = "Bangladesh"
print(country)

age = 26
print(age)

score = 9.5
print(score)

name = "Abdullah Saihan"
city = "Dhaka"

print("Hello, My name is ", name)
print("I'm from ", city)

"""## Basic Data Types

In Python, data can be of different types.
For now, we will learn the 4 most common types:

**1. String (str) — Text Data**

A string is used to store text.

You can write a string inside:

- double quotes → `"Hello"`

- single quotes → `'Python'`

Examples:

```python
name = "Saihan"
city = 'Dhaka'
```

Note that nything inside quotes becomes text, even numbers -

```python
age = "25"   # This is a string, not a number
```

**2️. Integer (int) — Whole Numbers**

Integers are numbers without decimal points.

Examples:
```python
age = 25
year = 2025
count = -5
```

**3️. Float (float) — Decimal Numbers**

Floats are numbers with decimal points.

Examples:
```python
price = 10.5
height = 5.9
temperature = -2.75
```

**4️.Boolean (bool) — True or False**

A Boolean stores either:

`True` or `False`

Examples:

```python
is_active = True
is_little = False
```

Booleans often come from comparisons:

```python
print(5 > 3)    # True
print(10 < 7)   # False
print(7 == 6)   # False
print(6 != 7)   # True
print(2 >= 5)   # False
print(6 <= 9)   # True
```

"""

age = 10
temparature = 34.5


name = "Saihan"
city = "Dhaka"


is_rainy = False
is_sunny = True



print(type(age))
print(type(temparature))
print(type(name))
print(type(city))
print(type(is_rainy))
print(type(is_sunny))

result = 4 > 5

print(result)
print(type(result))

## comparison operators
## boolean data often comes from comarison

print(5 > 3)    # 5 greater than 3 -> True
print(10 < 7)   # 10 less than 7 -> False
print(7 == 6)   # 7 equal to 6 -> False
print(6 != 7)   # 6 not equal to 7 -> True
print(2 >= 5)   # 2 greater than or equal to 5 -> False
print(6 <= 9)   # 6 less than or equal to 9 -> True

"""## Commenting in Python

Comments are notes in your code that are ignored by Python when the program runs.
They are used to explain code, make it readable, or temporarily disable code.



a) Inline comment
```python
x = 10  # Assign 10 to variable x
print(x)  # Print the value of x
```

b) Single-line comment
```python
# This is a single-line comment
print("Hello, Python!")
```

c) Multi-line comment
```python
# This is a multi-line comment
# explaining what the code does
# line by line
greet = "Hi"
name = "Zami"
print(f"{greet} {name}")
```
d) Commenting out code to temporarily prevent it from running
```python
# The following code cannot be run because it is commented out.

# greet = "Hi"
# name = "Zami"
# print(f"{greet} {name}")
```
"""

# This is a single-line comment
print("Welcome to Python!")  # Inline comment: prints welcome message


# This is a multi-line comment
# explaining the next few lines of code

greet = "Hello"
name = "Zami"
print(f"{greet} {name}")

# Commenting out code to temporarily disable it
# age = int(input("Enter your age: "))
# print("Your age is", age)

"""## Type Conversion

Type conversion means changing one data type into another.

Example: converting a string into an integer.

**Common conversions:**
```python
int("10")       # string → integer
float("10.5")   # string → float
str(25)         # integer → string
str(3.14)       # float → string
```

**`type()` Function**

type() tells you what data type a value or variable is.

Examples:
```python
print(type("Hello"))   # str
print(type(10))        # int
print(type(10.5))      # float
print(type(True))      # bool
```

**`"10"` is a String, NOT a Number**

Even though `"10"` looks like a number,
because it’s inside quotes, Python treats it as text (string).

```python
value = "10"
print(type(value))   # <class 'str'>

```

You cannot do math with it unless you convert it:

```python
a = "10"
b = 5

print(a + b)   # ❌ Error
```
Convert it first:
```python

print(int(a) + b)   # 15
```

"""

a = "10"        # a is a string
b = int(a)      # convert to integer

print(a)
print(type(a))
print(b)
print(type(b))

x = "10.5"      # x is a string
y = float(x)    # convert to float

print(x)
print(type(x))
print(y)
print(type(y))

num = 25           # num is a integer
text = str(num)   # convert to string

print(num)
print(type(num))
print(text)
print(type(text))

pi = 3.14           # pi is a float
pi_text = str(pi)   # convert to string

print(pi)
print(type(pi))
print(pi_text)
print(type(pi_text))

"""## Arithmatic and Comarison Operators

#### Arithmatic Operators

| Operator | Name                | What it does (Simple)                         | Example        | Result |
|----------|---------------------|-----------------------------------------------|----------------|--------|
| +        | Addition            | Adds two numbers                              | 5 + 3          | 8      |
| -        | Subtraction         | Subtracts one number from another             | 5 - 3          | 2      |
| *        | Multiplication      | Multiplies two numbers                        | 5 * 3          | 15     |
| /        | Division            | Divides and returns float                     | 5 / 2          | 2.5    |
| //       | Floor Division      | Divides and returns whole number (no decimal) | 5 // 2         | 2      |
| %        | Modulus             | Returns remainder of division                 | 5 % 2          | 1      |
| **       | Exponent (Power)    | Raises number to a power                      | 2 ** 3         | 8      |


**Quick notes:**
- `/` always returns a decimal (float)
- `//` removes the decimal part
- `%` is useful for checking even/odd numbers
- `**` means power (like 2**3 =  2³)


#### Comarison Operators

| Operator | Name                  | What it does (Simple)                  | Example        | Result |
|----------|-----------------------|----------------------------------------|----------------|--------|
| ==       | Equal to              | Checks if two values are equal         | 5 == 5         | True   |
| !=       | Not equal to          | Checks if two values are different     | 5 != 3         | True   |
| >        | Greater than          | Checks if left is bigger than right    | 5 > 3          | True   |
| <        | Less than             | Checks if left is smaller than right   | 5 < 3          | False  |
| >=       | Greater than or equal | Bigger OR equal                        | 5 >= 3         | True   |
| <=       | Less than or equal    | Smaller OR equal                       | 5 <= 3         | False  |


**Quick notes:**
- These operators always return True or False
- Used in if conditions, loops, and decision-making
"""

a = 50
b = 10

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(7/2) # normal division

print(7//2)  # floor division

a = 11
b = 3

print(a % b)

a = 3
b = 4

print(a**b)
print(3**4)
print(3*3*3*3)

print(5 > 3)    # 5 greater than 3 -> True
print(10 < 7)   # 10 less than 7 -> False
print(7 == 6)   # 7 equal to 6 -> False
print(6 != 7)   # 6 not equal to 7 -> True
print(2 >= 5)   # 2 greater than or equal to 5 -> False
print(6 <= 9)   # 6 less than or equal to 9 -> True

"""## Taking User Input in Python

In Python, we use the `input()` function to take data from the user.

**Basic Input**
```python
name = input()
```

This will wait for the user to type something and press Enter.
Whatever the user types is stored in the variable name.

**Input with a Message (Prompt)**

We usually show a message so the user knows what to type.

```python
name = input("Enter your name: ")
```


Example:

```shell
Enter your name: Saihan
```


Then `name` variable will store "Saihan".

**Important: input() Always Returns a String**

Even if the user types a number,
Python treats it as string (text).

Example:

```python
age = input("Enter your age: ")
print(type(age))   # str
```

If you want to use the input as a number, convert it:
```python
age = int(input("Enter your age: "))
```

or for decimal numbers:

```python
price = float(input("Enter the price: "))
```

"""

username = input("Please enter your username: ")
password = input("Please enter your password: ")
age = int(input("Please enter your age: "))

print(username)
print(type(username))

print(password)
print(type(password))

print(age)
print(type(age))

# input() -> always return strings

a = input("Enter first number: ")
b = input("Enter 2nd number: ")

print(a, b)
print(type(a))
print(type(b))

"""## String Concatenation and Repeataion

#### String Concatenation (+)
- Used to **join (add) two or more strings**
- Only works with strings (not numbers directly)

**Example:**
```python
print("Hello" + " " + "World")   # "Hello World"

name = "Sam"
print("Hello " + name)    #  "Hello Sam"
```

#### String Repetition (*)
- Used to **repeat a string multiple times**
- Multiply a string by a number

**Example:**
```python
print("Hi" * 3)        # "HiHiHi"
print("-" * 5)         # "-----"
```

#### Important Notes:
- You **cannot** add string and number directly:
  `"Age: " + 20`   ❌ Error

- Convert number to string first:
  `"Age: " + str(20)`   ✅ "Age: 20"
"""

first_name = "Abdullah"
last_name = "Saihan"


full_name = first_name + " " + last_name   # string concatenation
print(full_name)

print("="*20)  # string repeatation

"""## Output formatting using `print()`
The `print()` function is used to display output on the screen. Python provides several ways to format this output neatly and clearly.

#### Basic `print()`
   
You can print text, numbers, variables, or expressions.

```python
print("Hello Python")  # printing text
print(10)              # printing number
print(5 + 3)           # printing expression
name = "Hasnat"
print(name)            # printing variable
```
Output:
```shell
Hello Python
10
8
Hasnat
```
#### Printing multiple items using a single `print()`

You can print more multiple items by separating them with commas.

**printing multiple text/numbers**
```python
print("Hello", "World!")
print("Hello", 1234, "mic", "testing!")
```
Output:
```shell
Hello World!
Hello 1234 mic testing!
```
**printing multiple variables**
```python
a = 10
b = 20
c = 30
print(a, b, c)
```
Output:
```shell
10 20 30
```
**printing multiple text and variables together**
```python
name = "Zubayer"
age = 20
print("My name is", name, "I am", age, "years old")
```
Output:
```shell
My name is Zubayer I am 20 years old
```

#### `sep` (Separator)

The sep parameter defines how multiple values are separated when printed.

Default separator: `1 space ( ) --> sep=" "`
```python
print("10", "05", "2025", sep="-")
print("2025", "05", "2025", sep="/")
```
Output:
```shell
10-05-2025
10/05/2025
```


#### Escape Characters `e.g. \n, \t`

Escape characters are special characters used inside strings.

**a) New Line `\n`**

Moves the cursor to a new line.
```python
print("Hello\nWorld")
```
Output:
```shell
Hello
World
```

**b) Tab Space `\t`**

Adds horizontal spacing (tab).

```python
print("Name\tAge\tCity")
print("Ali\t25\tDhaka")
```

Output:

```shell
Name    Age     City
Ali     25      Dhaka
```

#### f-String (Formatted String)

f-strings allow you to insert variables directly inside strings.

```python
name = "Saihan"
age = 26
print(f"My name is {name} and I am {age} years old.")
```
Output:
```shell
My name is Saihan and I am 26 years old.
```

You can also use expressions:
```python
a = 10
b = 5
print(f"Sum = {a + b}")
```
Output:
```shell
Sum = 15
```

#### Number Formatting (int and float)

**a) Integer Formatting**

Leading zeros:

```python
num = 7
print(f"{num:03d}")
```
Output:
```shell
007
```

**b) Float Formatting**

Control decimal places:
```python
pi = 3.1415926
print(f"{pi:.2f}")
```

Output:
```shell
3.14
```

**c) Both together**
```python
price = 45.6789
quantity = 3
print(f"Quantity: {quantity:02d}, Price: {price:.2f}")
```
Output:
```shell
Quantity: 03, Price: 45.68
```

#### Printing same thing using multple ways
```python
name = "Saihan"
age = 26

print("Name:", name, "Age:" age)
print(f"Name: {name} Age: {age}")
```
Output:
```shell
Name: Saihan Age: 26
Name: Saihan Age: 26
```

```python
print("10", "07", "2025", sep="-")
print("10-07-2025")
```
Output:
```shell
10-07-2025
10-07-2025
```


```python
a = 10
b = 20
c = 30
print(a, "|", b, "|", c)
print(a, b, c, sep=" | ")
print(f"{a} | {b} | {c}")
```
Output:
```shell
10 | 20 | 30
10 | 20 | 30
10 | 20 | 30
```




#### Key Points

- Use comma ( , ) to print multiple items
- Python automatically adds a space between items
- sep controls how items are separated
- f-strings make output clean and readable
"""

a = 10
b = 20
c = 30
print(a, "|", b, "|", c)
print(a, b, c, sep=" | ")
print(f"{a} | {b} | {c}")

name = "Saihan"
age = 20
print("Name:", name)
print("Age:", age)
print("Name:", name, "Age:", age)

print("10", "01", "2000", sep="/")
print("10/01/2000")

print("10", "01", "2000", sep="-")
print("10-01-2000")

name = "Saihan"
age = 20
print("Name:\n", name, "\nAge:\n", age, sep="")

name = "Saihan"
age = 20
print("Name:", name, "\tAge:\t", age, sep=" ")

name = "Saihan"
age = 20
print("Name:\t", name, "\nAge:\t", age, sep=" ")

name = "Rayhan"
age = 18
workplace  = "banglalink"

print(f"Hi I'm {name}. \nI'm {age} years \t old, \nCurrenly I'm working at {workplace}")

si = 7
name = "Saihan"

print(f"{si:03}\t{name}")

price = 10.544342

print(f"Price: {price:.5f}")

# f-string


name = "Saihan"
city = "Dhaka"
age = 20


print("Hello, My name is ", name)
print("I'm from ", city)
print("I'm", age, "years old")

name = "Saihan"
city = "Dhaka"
age = 20

print(f"Hello, My name is {name}")
print(f"I'm from {city}")
print(f"I'm {age} years old")

print('His name is "Saihan", He is from Dhaka')
print("His name is 'Saihan', He is from Dhaka")

print()
print("Result")
print("="*30)
print(f"a+b = {a + b}")
print(f"a-b = {a - b}")
print(f"{a} x {b} = {a * b}")
print(f"{a} / {b} = {a / b}")

eval("2+3+10-9")

"""## Notes on Debugging Errors

Debugging means finding and fixing errors and mistakes in a program. For beginners, these three types of errors occur most often:
- Syntax Error
- Name Error
- Type Error

### Syntax Error

A Syntax Error occurs when Python cannot understand the code because it breaks the rules of the language.

**a) Missing Quote**
```python
print("Hello World)
```
Output:
```shell
SyntaxError: unterminated string literal
```

**b) Mixing Single Quote and Double Quote**
```python
print("Hello World')
```
Output:
```shell
SyntaxError: unterminated string literal
```

**c) Missing Parenthesis**
```python
print("Hello World"
```
Output:
```shell
SyntaxError: '(' was never closed
```

### Name Error

A Name Error occurs when you use a variable that has not been defined

**a) Undefined Variable**
```python
print(country)
```
Output:
```shell
NameError: name 'country' is not defined
```

**b) Misspelled Variable Name**
```python
number = 10
print(numbr)
```
Output:
```shell
NameError: name 'numbr' is not defined
```

**c) Using Variable Before Assignment**
```python
print(place)
place = "Dhanmondi"
```
Output:
```shell
NameError: name 'place' is not defined
```


### Type Error

A Type Error occurs when you perform an operation on incompatible data types.

**a) Unsupported Operand Type**
```python
num1 = 10
num2 = "5"  # notice that num2 is not actually a number, it is a string
print(num1 + num2)
```
Output:
```shell
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```




"""

a = "20"
b = "10"
print(a - b)

a = "20"
b = "10"
print(int(a) - int(b))

num1 = 10
num2 = "5"
print(num1 + num2)

num1 = 10
num2 = "5"
print(num1 + int(num2))

print('Hello World")

print("Hello World)

print("Hello World"

print("Hello World")

name = "Saihan"

print(f"Hello {naem}")

name = "Saihan"

print(f"Hello {name}")

num1 = 10
num2 = "3"

print(num1 + num2)

birth_year = input("Enter your birth year: ")
age = 2025 - birth_year

print(f"User is {age} years old")

birth_year = int(input("Enter your birth year: "))
age = 2025 - birth_year

print(f"User is {age} years old")

num1 = 10
num2 = 0

print(num1+num2)
print(num1/num2)

"""## Project: Simple Calculator"""

a = float(input("Enter 1st number: "))
b = float(input("Enter 2nd number: "))

print()
print("Result")
print("="*30)
print(f"Addition = {a + b}")
print(f"Subtration = {a - b}")
print(f"Multiplication = {a * b}")
print(f"Division = {a / b}")

